services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped
    networks:
      - app_network

  app_blue:
    build:
      context: ./mock-service
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE:-blue-v1.0.0}
      - PORT=3000
    ports:
      - "8081:3000"
    networks:
      - app_network
    restart: unless-stopped

  app_green:
    build:
      context: ./mock-service
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN:-green-v1.0.0}
      - PORT=3000
    ports:
      - "8082:3000"
    networks:
      - app_network
    restart: unless-stopped

  alert_watcher:
    build:
      context: ./alert-watcher
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2.0}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
    volumes:
      - nginx-logs:/var/log/nginx:ro
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx-logs: