version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped
    networks:
      - app_network

  app_blue:
    image: ${BLUE_IMAGE:-yimikaade/wonderful:latest}
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE:-blue-v1.0.0}
      - PORT=3000
    ports:
      - "8081:3000"
    networks:
      - app_network
    restart: unless-stopped

  app_green:
    image: ${GREEN_IMAGE:-yimikaade/wonderful:latest}
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN:-green-v1.0.0}
      - PORT=3000
    ports:
      - "8082:3000"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge